// Generated by build/gen-engine-data-manifest.py. Do not edit.

#ifndef BACKENDS_PLATFORM_LIBRETRO_ENGINE_DATA_MANIFEST_H
#define BACKENDS_PLATFORM_LIBRETRO_ENGINE_DATA_MANIFEST_H

struct LibretroEngineDataEntry {
	const char *name;
	unsigned int size;
};

static const LibretroEngineDataEntry s_engineDataManifest[] = {
	{ "access.dat", 520352u },
	{ "achievements.dat", 249239u },
	{ "bagel.dat", 20584u },
	{ "classicmacfonts.dat", 626103u },
	{ "cryo.dat", 12499u },
	{ "cryomni3d.dat", 70416u },
	{ "darkseed.dat", 37183u },
	{ "drascula.dat", 259625u },
	{ "eem.dat", 7654u },
	{ "encoding.dat", 179670u },
	{ "fonts-cjk.dat", 38277312u },
	{ "fonts-imgui.dat", 4000965u },
	{ "fonts.dat", 6449829u },
	{ "freescape.dat", 30124u },
	{ "got.aud", 11313u },
	{ "got.gfx", 288199u },
	{ "grim-patch.lab", 9341u },
	{ "hadesch_translations.dat", 431u },
	{ "helpdialog.zip", 207764u },
	{ "hugo.dat", 186866u },
	{ "kyra.dat", 2028520u },
	{ "lure.dat", 768832u },
	{ "macgui.dat", 65656u },
	{ "macs2_translation.dat", 183u },
	{ "macventure.dat", 4146u },
	{ "mm.dat", 280803u },
	{ "monkey4-patch.m4b", 2990u },
	{ "mort.dat", 76302u },
	{ "myst3.dat", 358287u },
	{ "nancy.dat", 255042u },
	{ "neverhood.dat", 23804u },
	{ "prince_translation.dat", 168060u },
	{ "queen.tbl", 1100505u },
	{ "sky.cpt", 419427u },
	{ "supernova.dat", 523211u },
	{ "teenagent.dat", 403315u },
	{ "titanic.dat", 3197968u },
	{ "tony.dat", 24584u },
	{ "toon.dat", 20996u },
	{ "ultima.dat", 15981464u },
	{ "ultima8.dat", 238149u },
	{ "wintermute.zip", 4520u },
};

static const unsigned int s_engineDataManifestCount = 42u;

#endif
